name: rmsf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.1.1=0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.4.5.1=py38_0
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.2=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.64.2=h6f030ca_1
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=he1b5a44_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.6=nompi_h3c11f04_100
  - icu=64.2=he1b5a44_1
  - intel-openmp=2020.1=217
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=15_mkl
  - liblapacke=3.8.0=15_mkl
  - libllvm9=9.0.1=he513fc3_1
  - libopencv=4.2.0=py38_6
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.2=he1b5a44_1
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - olefile=0.46=py_0
  - opencv=4.2.0=py38_6
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1g=h7b6447c_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.1.2=py38hb39fc2d_0
  - pip=20.0.2=py38_3
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - py-opencv=4.2.0=py38h23f93f0_6
  - python=3.8.2=he5300dc_7_cpython
  - python_abi=3.8=1_cp38
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=h7b6447c_0
  - setuptools=46.4.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.10=hed695b0_0
  - wheel=0.34.2=py38_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h6597ccf_3
prefix: /home/edgar/miniconda3/envs/rmsf

